export const SIGNIN="SIGNIN";
export const DELIVERIES="DELIVERIES";
export const DASHBOARD="DASHBOARD";
export const DATECHANGE="DATECHANGE";
export const POPOVERCHANGE="POPOVERCHANGE";
export const BUTTONCLICK="BUTTONCLICK";
export const LOADER="LOADER";

//SHIPMENT TREND
export const SHIPPMENTTREND="SHIPPMENTTREND";
export const SHIPLOADER="SHIPLOADER";
export const SUMMARYDATE="SUMMARYDATE";
export const SHIPBUTTONCLICK="SHIPBUTTONCLICK";
export const POPOVERSHIPCHANGE="POPOVERSHIPCHANGE";



//SETTLEMENT//
export const FETCHSETTLEMENT="FETCHSETTLEMENT";

//STATEMENTS
export const FETCH_STATEMENTS="FETCH_STATEMENTS";
